# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import math

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(958, 674)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.depCodeComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_0.setGeometry(QtCore.QRect(10, 20, 85, 20))
        self.depCodeComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_0.setMaxVisibleItems(10)
        self.depCodeComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_0.setObjectName("depCodeComboBox_0")
        self.schedule = QtWidgets.QTableWidget(self.centralwidget)
        self.schedule.setEnabled(True)
        self.schedule.setGeometry(QtCore.QRect(10, 230, 472, 377))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule.sizePolicy().hasHeightForWidth())
        self.schedule.setSizePolicy(sizePolicy)
        self.schedule.setMinimumSize(QtCore.QSize(0, 0))
        self.schedule.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.schedule.setFont(font)
        self.schedule.setLineWidth(1)
        self.schedule.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.schedule.setGridStyle(QtCore.Qt.SolidLine)
        self.schedule.setRowCount(14)
        self.schedule.setColumnCount(5)
        self.schedule.setObjectName("schedule")
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(4, item)
        self.schedule.horizontalHeader().setCascadingSectionResizes(False)
        self.schedule.horizontalHeader().setDefaultSectionSize(77)
        self.schedule.horizontalHeader().setMinimumSectionSize(77)
        self.schedule.horizontalHeader().setStretchLastSection(True)
        self.schedule.verticalHeader().setVisible(True)
        self.schedule.verticalHeader().setDefaultSectionSize(25)
        self.schedule.verticalHeader().setStretchLastSection(True)
        self.depCodeComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_1.setGeometry(QtCore.QRect(10, 40, 85, 20))
        self.depCodeComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_1.setMaxVisibleItems(10)
        self.depCodeComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_1.setObjectName("depCodeComboBox_1")
        self.depCodeComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_2.setGeometry(QtCore.QRect(10, 60, 85, 20))
        self.depCodeComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_2.setMaxVisibleItems(10)
        self.depCodeComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_2.setObjectName("depCodeComboBox_2")
        self.depCodeComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_3.setGeometry(QtCore.QRect(10, 80, 85, 20))
        self.depCodeComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_3.setMaxVisibleItems(10)
        self.depCodeComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_3.setObjectName("depCodeComboBox_3")
        self.depCodeComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_4.setGeometry(QtCore.QRect(10, 100, 85, 20))
        self.depCodeComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_4.setMaxVisibleItems(10)
        self.depCodeComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_4.setObjectName("depCodeComboBox_4")
        self.depCodeComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_5.setGeometry(QtCore.QRect(10, 120, 85, 20))
        self.depCodeComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_5.setMaxVisibleItems(10)
        self.depCodeComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_5.setObjectName("depCodeComboBox_5")
        self.depCodeComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_6.setGeometry(QtCore.QRect(10, 140, 85, 20))
        self.depCodeComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_6.setMaxVisibleItems(10)
        self.depCodeComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_6.setObjectName("depCodeComboBox_6")
        self.depCodeComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_7.setGeometry(QtCore.QRect(10, 160, 85, 20))
        self.depCodeComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_7.setMaxVisibleItems(10)
        self.depCodeComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_7.setObjectName("depCodeComboBox_7")
        self.depCodeComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_8.setGeometry(QtCore.QRect(10, 180, 85, 20))
        self.depCodeComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_8.setMaxVisibleItems(10)
        self.depCodeComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_8.setObjectName("depCodeComboBox_8")
        self.depCodeComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_9.setGeometry(QtCore.QRect(10, 200, 85, 20))
        self.depCodeComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_9.setMaxVisibleItems(10)
        self.depCodeComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_9.setObjectName("depCodeComboBox_9")
        self.classCodeComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_0.setGeometry(QtCore.QRect(100, 20, 101, 20))
        self.classCodeComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_0.setMaxVisibleItems(10)
        self.classCodeComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_0.setObjectName("classCodeComboBox_0")
        self.classCodeComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_1.setGeometry(QtCore.QRect(100, 40, 101, 20))
        self.classCodeComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_1.setMaxVisibleItems(10)
        self.classCodeComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_1.setObjectName("classCodeComboBox_1")
        self.classCodeComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_2.setGeometry(QtCore.QRect(100, 60, 101, 20))
        self.classCodeComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_2.setMaxVisibleItems(10)
        self.classCodeComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_2.setObjectName("classCodeComboBox_2")
        self.classCodeComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_3.setGeometry(QtCore.QRect(100, 80, 101, 20))
        self.classCodeComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_3.setMaxVisibleItems(10)
        self.classCodeComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_3.setObjectName("classCodeComboBox_3")
        self.classCodeComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_4.setGeometry(QtCore.QRect(100, 100, 101, 20))
        self.classCodeComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_4.setMaxVisibleItems(10)
        self.classCodeComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_4.setObjectName("classCodeComboBox_4")
        self.classCodeComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_5.setGeometry(QtCore.QRect(100, 120, 101, 20))
        self.classCodeComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_5.setMaxVisibleItems(10)
        self.classCodeComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_5.setObjectName("classCodeComboBox_5")
        self.classCodeComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_6.setGeometry(QtCore.QRect(100, 140, 101, 20))
        self.classCodeComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_6.setMaxVisibleItems(10)
        self.classCodeComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_6.setObjectName("classCodeComboBox_6")
        self.classCodeComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_7.setGeometry(QtCore.QRect(100, 160, 101, 20))
        self.classCodeComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_7.setMaxVisibleItems(10)
        self.classCodeComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_7.setObjectName("classCodeComboBox_7")
        self.classCodeComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_8.setGeometry(QtCore.QRect(100, 180, 101, 20))
        self.classCodeComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_8.setMaxVisibleItems(10)
        self.classCodeComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_8.setObjectName("classCodeComboBox_8")
        self.classCodeComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_9.setGeometry(QtCore.QRect(100, 200, 101, 20))
        self.classCodeComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_9.setMaxVisibleItems(10)
        self.classCodeComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_9.setObjectName("classCodeComboBox_9")
        self.availClassComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_0.setGeometry(QtCore.QRect(210, 20, 741, 20))
        self.availClassComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_0.setMaxVisibleItems(10)
        self.availClassComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_0.setObjectName("availClassComboBox_0")
        self.availClassComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_1.setGeometry(QtCore.QRect(210, 40, 741, 20))
        self.availClassComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_1.setMaxVisibleItems(10)
        self.availClassComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_1.setObjectName("availClassComboBox_1")
        self.availClassComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_2.setGeometry(QtCore.QRect(210, 60, 741, 20))
        self.availClassComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_2.setMaxVisibleItems(10)
        self.availClassComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_2.setObjectName("availClassComboBox_2")
        self.availClassComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_3.setGeometry(QtCore.QRect(210, 80, 741, 20))
        self.availClassComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_3.setMaxVisibleItems(10)
        self.availClassComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_3.setObjectName("availClassComboBox_3")
        self.availClassComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_4.setGeometry(QtCore.QRect(210, 100, 741, 20))
        self.availClassComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_4.setMaxVisibleItems(10)
        self.availClassComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_4.setObjectName("availClassComboBox_4")
        self.availClassComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_5.setGeometry(QtCore.QRect(210, 120, 741, 20))
        self.availClassComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_5.setMaxVisibleItems(10)
        self.availClassComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_5.setObjectName("availClassComboBox_5")
        self.availClassComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_6.setGeometry(QtCore.QRect(210, 140, 741, 20))
        self.availClassComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_6.setMaxVisibleItems(10)
        self.availClassComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_6.setObjectName("availClassComboBox_6")
        self.availClassComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_7.setGeometry(QtCore.QRect(210, 160, 741, 20))
        self.availClassComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_7.setMaxVisibleItems(10)
        self.availClassComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_7.setObjectName("availClassComboBox_7")
        self.availClassComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_8.setGeometry(QtCore.QRect(210, 180, 741, 20))
        self.availClassComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_8.setMaxVisibleItems(10)
        self.availClassComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_8.setObjectName("availClassComboBox_8")
        self.availClassComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_9.setGeometry(QtCore.QRect(210, 200, 741, 20))
        self.availClassComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_9.setMaxVisibleItems(10)
        self.availClassComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_9.setObjectName("availClassComboBox_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 0, 331, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Program = QtWidgets.QMenu(self.menubar)
        self.menu_Program.setObjectName("menu_Program")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_asdasd = QtWidgets.QAction(MainWindow)
        self.action_asdasd.setObjectName("action_asdasd")
        self.action_Reset = QtWidgets.QAction(MainWindow)
        self.action_Reset.setObjectName("action_Reset")
        self.action_Update_database = QtWidgets.QAction(MainWindow)
        self.action_Update_database.setObjectName("action_Update_database")
        self.action_Load = QtWidgets.QAction(MainWindow)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.menuFile.addAction(self.action_Load)
        self.menuFile.addAction(self.action_Save)
        self.menu_Program.addAction(self.action_Reset)
        self.menu_Program.addAction(self.action_Update_database)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Program.menuAction())
        for i in range(0,70):
            self.schedule.setItem(i%14,math.floor(i/14),QtWidgets.QTableWidgetItem())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ITU Programci"))
        item = self.schedule.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "8:30-9:29"))
        item = self.schedule.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "9:30-10:29"))
        item = self.schedule.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10:30-11:29"))
        item = self.schedule.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "11:30-12:29"))
        item = self.schedule.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "12:30-13:29"))
        item = self.schedule.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "13:30-14:29"))
        item = self.schedule.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "14:30-15:29"))
        item = self.schedule.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "15:30-16:29"))
        item = self.schedule.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "16:30-17:29"))
        item = self.schedule.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "17:30-18:29"))
        item = self.schedule.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "18:30-19:29"))
        item = self.schedule.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "19:30-20:29"))
        item = self.schedule.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "20:30-21:29"))
        item = self.schedule.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "21:30-22:29"))
        item = self.schedule.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pazartesi"))
        item = self.schedule.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sali"))
        item = self.schedule.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Carsamba"))
        item = self.schedule.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Persembe"))
        item = self.schedule.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cuma"))
        self.label.setText(_translate("MainWindow", "Bolum"))
        self.label_2.setText(_translate("MainWindow", "Ders Kodu"))
        self.label_3.setText(_translate("MainWindow", "Acilan Dersler"))
        self.menuFile.setTitle(_translate("MainWindow", "&Dosya"))
        self.menu_Program.setTitle(_translate("MainWindow", "&Program"))
        self.action_asdasd.setText(_translate("MainWindow", "&Ac"))
        self.action_Reset.setText(_translate("MainWindow", "&Sifirla"))
        self.action_Update_database.setText(_translate("MainWindow", "&Veritabanini guncelle"))
        self.action_Load.setText(_translate("MainWindow", "&Ac"))
        self.action_Save.setText(_translate("MainWindow", "&Kaydet"))
