# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(994, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.depCodeComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_0.setGeometry(QtCore.QRect(10, 10, 85, 25))
        self.depCodeComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_0.setMaxVisibleItems(10)
        self.depCodeComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_0.setObjectName("depCodeComboBox_0")
        self.schedule = QtWidgets.QTableWidget(self.centralwidget)
        self.schedule.setEnabled(True)
        self.schedule.setGeometry(QtCore.QRect(10, 310, 606, 451))
        self.schedule.setGridStyle(QtCore.Qt.SolidLine)
        self.schedule.setRowCount(14)
        self.schedule.setColumnCount(5)
        self.schedule.setObjectName("schedule")
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule.setHorizontalHeaderItem(4, item)
        self.depCodeComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_1.setGeometry(QtCore.QRect(10, 40, 85, 25))
        self.depCodeComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_1.setMaxVisibleItems(10)
        self.depCodeComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_1.setObjectName("depCodeComboBox_1")
        self.depCodeComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_2.setGeometry(QtCore.QRect(10, 70, 85, 25))
        self.depCodeComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_2.setMaxVisibleItems(10)
        self.depCodeComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_2.setObjectName("depCodeComboBox_2")
        self.depCodeComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_3.setGeometry(QtCore.QRect(10, 100, 85, 25))
        self.depCodeComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_3.setMaxVisibleItems(10)
        self.depCodeComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_3.setObjectName("depCodeComboBox_3")
        self.depCodeComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_4.setGeometry(QtCore.QRect(10, 130, 85, 25))
        self.depCodeComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_4.setMaxVisibleItems(10)
        self.depCodeComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_4.setObjectName("depCodeComboBox_4")
        self.depCodeComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_5.setGeometry(QtCore.QRect(10, 160, 85, 25))
        self.depCodeComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_5.setMaxVisibleItems(10)
        self.depCodeComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_5.setObjectName("depCodeComboBox_5")
        self.depCodeComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_6.setGeometry(QtCore.QRect(10, 190, 85, 25))
        self.depCodeComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_6.setMaxVisibleItems(10)
        self.depCodeComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_6.setObjectName("depCodeComboBox_6")
        self.depCodeComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_7.setGeometry(QtCore.QRect(10, 220, 85, 25))
        self.depCodeComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_7.setMaxVisibleItems(10)
        self.depCodeComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_7.setObjectName("depCodeComboBox_7")
        self.depCodeComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_8.setGeometry(QtCore.QRect(10, 250, 85, 25))
        self.depCodeComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_8.setMaxVisibleItems(10)
        self.depCodeComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_8.setObjectName("depCodeComboBox_8")
        self.depCodeComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.depCodeComboBox_9.setGeometry(QtCore.QRect(10, 280, 85, 25))
        self.depCodeComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.depCodeComboBox_9.setMaxVisibleItems(10)
        self.depCodeComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.depCodeComboBox_9.setObjectName("depCodeComboBox_9")
        self.classCodeComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_0.setGeometry(QtCore.QRect(110, 10, 101, 25))
        self.classCodeComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_0.setMaxVisibleItems(10)
        self.classCodeComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_0.setObjectName("classCodeComboBox_0")
        self.classCodeComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_1.setGeometry(QtCore.QRect(110, 40, 101, 25))
        self.classCodeComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_1.setMaxVisibleItems(10)
        self.classCodeComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_1.setObjectName("classCodeComboBox_1")
        self.classCodeComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_2.setGeometry(QtCore.QRect(110, 70, 101, 25))
        self.classCodeComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_2.setMaxVisibleItems(10)
        self.classCodeComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_2.setObjectName("classCodeComboBox_2")
        self.classCodeComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_3.setGeometry(QtCore.QRect(110, 100, 101, 25))
        self.classCodeComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_3.setMaxVisibleItems(10)
        self.classCodeComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_3.setObjectName("classCodeComboBox_3")
        self.classCodeComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_4.setGeometry(QtCore.QRect(110, 130, 101, 25))
        self.classCodeComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_4.setMaxVisibleItems(10)
        self.classCodeComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_4.setObjectName("classCodeComboBox_4")
        self.classCodeComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_5.setGeometry(QtCore.QRect(110, 160, 101, 25))
        self.classCodeComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_5.setMaxVisibleItems(10)
        self.classCodeComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_5.setObjectName("classCodeComboBox_5")
        self.classCodeComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_6.setGeometry(QtCore.QRect(110, 190, 101, 25))
        self.classCodeComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_6.setMaxVisibleItems(10)
        self.classCodeComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_6.setObjectName("classCodeComboBox_6")
        self.classCodeComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_7.setGeometry(QtCore.QRect(110, 220, 101, 25))
        self.classCodeComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_7.setMaxVisibleItems(10)
        self.classCodeComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_7.setObjectName("classCodeComboBox_7")
        self.classCodeComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_8.setGeometry(QtCore.QRect(110, 250, 101, 25))
        self.classCodeComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_8.setMaxVisibleItems(10)
        self.classCodeComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_8.setObjectName("classCodeComboBox_8")
        self.classCodeComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.classCodeComboBox_9.setGeometry(QtCore.QRect(110, 280, 101, 25))
        self.classCodeComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.classCodeComboBox_9.setMaxVisibleItems(10)
        self.classCodeComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.classCodeComboBox_9.setObjectName("classCodeComboBox_9")
        self.availClassComboBox_0 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_0.setGeometry(QtCore.QRect(230, 10, 741, 25))
        self.availClassComboBox_0.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_0.setMaxVisibleItems(10)
        self.availClassComboBox_0.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_0.setObjectName("availClassComboBox_0")
        self.availClassComboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_1.setGeometry(QtCore.QRect(230, 40, 741, 25))
        self.availClassComboBox_1.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_1.setMaxVisibleItems(10)
        self.availClassComboBox_1.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_1.setObjectName("availClassComboBox_1")
        self.availClassComboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_2.setGeometry(QtCore.QRect(230, 70, 741, 25))
        self.availClassComboBox_2.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_2.setMaxVisibleItems(10)
        self.availClassComboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_2.setObjectName("availClassComboBox_2")
        self.availClassComboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_3.setGeometry(QtCore.QRect(230, 100, 741, 25))
        self.availClassComboBox_3.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_3.setMaxVisibleItems(10)
        self.availClassComboBox_3.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_3.setObjectName("availClassComboBox_3")
        self.availClassComboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_4.setGeometry(QtCore.QRect(230, 130, 741, 25))
        self.availClassComboBox_4.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_4.setMaxVisibleItems(10)
        self.availClassComboBox_4.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_4.setObjectName("availClassComboBox_4")
        self.availClassComboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_5.setGeometry(QtCore.QRect(230, 160, 741, 25))
        self.availClassComboBox_5.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_5.setMaxVisibleItems(10)
        self.availClassComboBox_5.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_5.setObjectName("availClassComboBox_5")
        self.availClassComboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_6.setGeometry(QtCore.QRect(230, 190, 741, 25))
        self.availClassComboBox_6.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_6.setMaxVisibleItems(10)
        self.availClassComboBox_6.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_6.setObjectName("availClassComboBox_6")
        self.availClassComboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_7.setGeometry(QtCore.QRect(230, 220, 741, 25))
        self.availClassComboBox_7.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_7.setMaxVisibleItems(10)
        self.availClassComboBox_7.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_7.setObjectName("availClassComboBox_7")
        self.availClassComboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_8.setGeometry(QtCore.QRect(230, 250, 741, 25))
        self.availClassComboBox_8.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_8.setMaxVisibleItems(10)
        self.availClassComboBox_8.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_8.setObjectName("availClassComboBox_8")
        self.availClassComboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.availClassComboBox_9.setGeometry(QtCore.QRect(230, 280, 741, 25))
        self.availClassComboBox_9.setStyleSheet("combobox-popup: 0;")
        self.availClassComboBox_9.setMaxVisibleItems(10)
        self.availClassComboBox_9.setIconSize(QtCore.QSize(16, 16))
        self.availClassComboBox_9.setObjectName("availClassComboBox_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 29))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_asdasd = QtWidgets.QAction(MainWindow)
        self.action_asdasd.setObjectName("action_asdasd")
        self.menuDosya.addAction(self.action_asdasd)
        self.menuDosya.addSeparator()
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ITU Programci"))
        item = self.schedule.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "8:30-9:29"))
        item = self.schedule.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "9:30-10:29"))
        item = self.schedule.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "10:30-11:29"))
        item = self.schedule.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "11:30-12:29"))
        item = self.schedule.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "12:30-13:29"))
        item = self.schedule.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "13:30-14:29"))
        item = self.schedule.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "14:30-15:29"))
        item = self.schedule.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "15:30-16:29"))
        item = self.schedule.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "16:30-17:29"))
        item = self.schedule.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "17:30-18:29"))
        item = self.schedule.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "18:30-19:29"))
        item = self.schedule.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "19:30-20:29"))
        item = self.schedule.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "20:30-21:29"))
        item = self.schedule.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "21:30-22:29"))
        item = self.schedule.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pazartesi"))
        item = self.schedule.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sali"))
        item = self.schedule.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Carsamba"))
        item = self.schedule.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Persembe"))
        item = self.schedule.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cuma"))
        self.menuDosya.setTitle(_translate("MainWindow", "&Dosya"))
        self.action_asdasd.setText(_translate("MainWindow", "&asdasd"))
